### ISSUE TITLE
m-team转种默认http，但是https才能正常运行

### ISSUE THREAD

**Issue by lyj0309** [ledccn/IYUUPlus#100]
version
![image](https://user-images.githubusercontent.com/50474995/204095974-7ad5dcc5-2c6e-4ec3-8fdd-0c78e2972224.png)

拿iyuu转钟时，默认会转成http的种子，但是下载不了，会报错
![image](https://user-images.githubusercontent.com/50474995/204095994-834ea29e-ceab-48e5-95ec-42559d55206b.png)

需要手动改成https类型的

能够修复下吗

**Comment by lcylgs** [comment]
站点设置的附加参数勾选HTTPS即可

**Comment by lyj0309** [comment]
> 站点设置的附加参数勾选HTTPS即可

知道了，感谢
