### ISSUE TITLE
请问可以适配一下SharkPT吗？

### ISSUE THREAD

**Issue by Xeorszj** [ledccn/IYUUPlus#104]
RT 这是我们站点的简介：
SharkPT成立于 2022 年 12 月，站点主打高品质资源，资源做到搜索、下载、刮削、识别一条龙服务，每一位进站的鲨友们不再为刮削苦恼、不再为海报墙发愁，论坛功能逐渐完善，各种细致教程，SharkPT解君愁。

站点官组：Shark、SharkWEB、SharkDIY、SharkTV、SharkMV。

注册现状：目前处于开注/低等级邀请制

站点招聘：欢迎各位有志之士参与建设SharkPT，一起成为鲨友，工作组待遇丰厚，您若是有所才能，不必迟疑，联系管理组即可。

目前官组资源正在稳步上升，主要以web资源为主。在考察玩家痛点后我们打出了一条龙、易刮削的资源特点；为那些因网络不畅等问题没法顺畅拥有自己的海报墙的玩家提供便利，同时造福普通玩家减轻了刮削带来的种种不便。我们预计近期开放注册。为方便各大Pter辅种增加连通性，我们希望大佬可以百忙之中为我们的站点进行适配。感谢！
这是我们站点的域名[https://sharkpt.net/，如果您需要邀请进站/权限可以联系qq：3170312119/tg：t.me/Mikkop_v](https://sharkpt.net/%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%82%A8%E9%9C%80%E8%A6%81%E9%82%80%E8%AF%B7%E8%BF%9B%E7%AB%99/%E6%9D%83%E9%99%90%E5%8F%AF%E4%BB%A5%E8%81%94%E7%B3%BBqq%EF%BC%9A3170312119/tg%EF%BC%9At.me/Mikkop_v)
同时我们祝IYUU越做越好，感谢开发者们为Pter们的付出~

@Xeorszj

**Comment by aknife2019** [comment]
你家为什么不允许live.com、live.cn 邮箱。。。

**Comment by luoxiao-xy** [comment]
同求，很漂亮的PT站

**Comment by Zeaglefly** [comment]
同求，很不错的PT新站，发展很快

**Comment by Xeorszj** [comment]
已支持，关闭本issue
