### ISSUE TITLE
请求支持Flood/RTorrent客户端

### ISSUE THREAD

**Issue by sabersalv** [ledccn/IYUUPlus#11]
rtorrent性能爆表, flood非常美观

**Comment by sabersalv** [comment]
自己写了一个 https://github.com/sabersalv/IYUU-GUI/pull/1

**Comment by ledccn** [comment]
感谢反馈，我研究一下客户端的API。

**Comment by sabersalv** [comment]
感谢, API文档可以看这里https://github.com/sabersalv/flood-api
