### ISSUE TITLE
api返回错误reseed_check导致部分站点无法辅种

### ISSUE THREAD

**Issue by BlueSkyClouds** [ledccn/IYUUPlus#111]
2xFree
鲨鱼
铂金学院

`reseed_check`错误设置成cookie 导致无法辅种

![23](https://user-images.githubusercontent.com/39831773/216392121-0ed0894f-4da2-4cbf-86d2-56c27ac13ec5.png)

**Comment by heroininu** [comment]
同碰到此问题，且下载链接的passKey没有被填充
