### ISSUE TITLE
如何进入容器内部查看失败详情？

### ISSUE THREAD

**Issue by leic4u** [ledccn/IYUUPlus#112]
看到失败日志在 ./torrent/cache/reseedError.txt 路径下，但是使用 docker exec -it iyuu bash 命令无法进入容器内部。在映射的 DB 文件夹下也找不到这个文件。
群晖的 docker 环境

**Comment by leic4u** [comment]
找到了，用 /bin/sh 可以进入容器，但没找到这个文件在哪

**Comment by leic4u** [comment]
找到了，完整路径是 /IYUU/runtime/torrent/cache/reseedError.txt

**Comment by PickTimbersaw** [comment]
有帮助，感谢~~
