### ISSUE TITLE
登录时怎么只有6个站点？

### ISSUE THREAD

**Issue by chenjingchun** [ledccn/IYUUPlus#121]
![image](https://user-images.githubusercontent.com/4917940/224906721-bbcce245-72d1-4ff9-a488-2d43ce71d470.png)
请问：现在只支持这6个站吗？
我没有这些站的账号（我只有hdtime和carpt），要怎么使用？

**Comment by kklod** [comment]
请问你是怎么解决的？  我也摸不着头脑~~@chenjingchun

**Comment by werran2** [comment]
请问你是怎么解决的？ 我也摸不着头脑~~@chenjingchun

**Comment by kklod** [comment]
> 请问你是怎么解决的？ 我也摸不着头脑~~@chenjingchun

这软件就是要有他支持认证的站点的账号才行   对新人不友好
