### ISSUE TITLE
请问Docker安装的项目如何跳过用户验证？或者添加验证站点？

### ISSUE THREAD

**Issue by dood2020** [ledccn/IYUUPlus#13]
已申请token，但是卡在用户验证...用户验证默认的6个站点中没有我当前使用的PT站，请问如何跳过或者添加站点？

尝试通过修改recommended.json文件添加PT站，但是启用iyuuplus时，该文件会被覆盖还原。

**Comment by dood2020** [comment]
备注：使用的设备为群晖NAS

**Comment by dood2020** [comment]
备注：目前使用的PT站在兼容列表内

**Comment by tmrsm** [comment]
> 已申请token，但是卡在用户验证...用户验证默认的6个站点中没有我当前使用的PT站，请问如何跳过或者添加站点？
> 
> 尝试通过修改recommended.json文件添加PT站，但是启用iyuuplus时，该文件会被覆盖还原。

合作站務必要有一個，如果手邊都沒符合的，hd.ai目前開放註冊中。
