### ISSUE TITLE
无法完成辅种任务，提示“没有查询到可辅种数据”

### ISSUE THREAD

**Issue by bhiaibogf** [ledccn/IYUUPlus#141]
环境：
宿主机是 unraid，qb、IYUUPlus 部署在 docker 内

任务日志：
![image](https://github.com/ledccn/IYUUPlus/assets/17107229/681d88a1-4fa2-4d89-b883-2bf068bcc911)
同时辅种日志是空的，微信也没有信息推送

其他测试结果：
docker 内可以 ping 通 api.iyuu.cn
转种任务正常，同时微信可以收到完成的通知
通过 api 测试了正在做种的种子，可以查询到辅种信息
![image](https://github.com/ledccn/IYUUPlus/assets/17107229/672b8c99-3120-4262-85b0-85a8ea55cae5)

**Comment by cjwddtc** [comment]
你可以选一个需要辅种的种子，用https://api.iyuu.cn/docs.php?service=App.Api.GetSubject&detail=1&type=fold这个api试一下，看是不是查的到，他这个数据库似乎是有延迟的。

**Comment by bhiaibogf** [comment]
看起来是网络问题，换了个网络环境之后工作正常了。
