### ISSUE TITLE
请问,现在新用户无法注册了吗

### ISSUE THREAD

**Issue by icegita** [ledccn/IYUUPlus#164]
已经打不开获取token的页面了,T_T

**Comment by Ling128** [comment]
同问

**Comment by tiancandevloper** [comment]
同问，打开页面提示网站未备案

**Comment by lk-timeout** [comment]
楼上+1

**Comment by BackspaceM** [comment]
可以自己先反代api.iyuu.cn用着

**Comment by ylqjgm** [comment]
> 可以自己先反代api.iyuu.cn用着

现在是未备案状态，请问要怎么反代？有其他ip地址么？

**Comment by BackspaceM** [comment]
> > 可以自己先反代api.iyuu.cn用着
> 
> 现在是未备案状态，请问要怎么反代？有其他ip地址么？

可以自己劫持一下api.iyuu.cn，ip指向45.66.217.239，也可以改hosts
