### ISSUE TITLE
api.iyuu.cn 挂了

### ISSUE THREAD

**Issue by AceInAndroid** [ledccn/IYUUPlus#165]
api.iyuu.cn 挂了

webui提示 无法访问https://api.iyuu.cn接口

HOST模式

 sudo docker exec -it iyuucn-iyuuplus-1 /bin/sh

/IYUU # curl -I api.iyuu.cn
HTTP/1.1 403 Forbidden
Server: Beaver
Cache-Control: no-cache
Content-Type: text/html
Content-Length: 635
Connection: close

/IYUU # wget --spider api.iyuu.cn
Spider mode enabled. Check if remote file exists.
--2024-01-15 11:42:16--  http://api.iyuu.cn/
Resolving api.iyuu.cn (api.iyuu.cn)... 120.25.193.2
Connecting to api.iyuu.cn (api.iyuu.cn)|120.25.193.2|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
Remote file does not exist -- broken link!!!

/IYUU # 

网络正常  ping百度正常

 ping baidu.com
PING baidu.com (39.156.66.10): 56 data bytes
64 bytes from 39.156.66.10: seq=0 ttl=53 time=41.679 ms
64 bytes from 39.156.66.10: seq=1 ttl=53 time=41.201 ms
64 bytes from 39.156.66.10: seq=2 ttl=53 time=42.126 ms
64 bytes from 39.156.66.10: seq=3 ttl=53 time=41.946 ms
64 bytes from 39.156.66.10: seq=4 ttl=53 time=42.843 ms

curl baidu正常  
网络正常

/IYUU # curl -I baidu.com
HTTP/1.1 200 OK
Date: Mon, 15 Jan 2024 03:47:34 GMT
Server: Apache
Last-Modified: Tue, 12 Jan 2010 13:48:00 GMT
ETag: "51-47cf7e6ee8400"
Accept-Ranges: bytes
Content-Length: 81
Cache-Control: max-age=86400
Expires: Tue, 16 Jan 2024 03:47:34 GMT
Connection: Keep-Alive
Content-Type: text/html

**Comment by chixinzei** [comment]
同样挂了

**Comment by AceInAndroid** [comment]
解决了 在本地自建IYUU反向代理，然后自签证书，修改域名host即可正常恢复 

首先
1、自签iyuu证书  
2、然后Nginx 创建iyuu反向代理 
3、映射证书文件到iyuu容器上

具体看https://invites.fun/d/19949

**Comment by AceInAndroid** [comment]
> 同样挂了

解决了 要反代一下

**Comment by Qiqia** [comment]
> 解决了 在本地自建IYUU反向代理，然后自签证书，修改域名host即可正常恢复
> 
> 首先 1、自签iyuu证书 2、然后Nginx 创建iyuu反向代理 3、映射证书文件到iyuu容器上
> 
> 具体看https://invites.fun/d/19949

失效了 emm
