### ISSUE TITLE
朱雀认证失败

### ISSUE THREAD

**Issue by Rick630** [ledccn/IYUUPlus#171]
![image](https://github.com/ledccn/IYUUPlus/assets/11673596/d25a1c2b-2a6b-4a19-808a-33eda964a244)

**Comment by guyanyouyou** [comment]
大佬咋成功的，我也是认证失败，卡这了

**Comment by Rick630** [comment]
> 大佬咋成功的，我也是认证失败，卡这了

检查下你朱雀等级是否达到可验证iyuu的要求
