### ISSUE TITLE
本地登录报token错误，检查是否设置拒收

### ISSUE THREAD

**Issue by MonRain** [ledccn/IYUUPlus#173]
群晖拉取docker版本IYUU，登录8787 webUI，输入token后报错
![QQ截图20240404153858](https://github.com/ledccn/IYUUPlus/assets/50914567/eb96470c-3752-4057-8f6d-5e5a24d13f66)

token是通过微信扫码获取的

**Comment by StarGods** [comment]
同

**Comment by wangym3000** [comment]
同样问题，极空间拉取最新版本。

**Comment by 1219099256** [comment]
好像服务出问题了吧，公众号功能里面没有通知设置了，只剩下一个拍照

**Comment by wangym3000** [comment]
已经修复

**Comment by 1219099256** [comment]
我还是用不了

**Comment by xt683501** [comment]
我也是，但不知怎么突然又能用了

**Comment by SouthWindLoki** [comment]
同个问题蹲一个解决方案

**Comment by Yuhanlll** [comment]
同样的问题，有好兄弟解决了吗

**Comment by Yuhanlll** [comment]
> 已经修复

哥们儿能提供下解决方案吗

**Comment by 1219099256** [comment]
你们都是部署在海外服务器的吗，有没有部署在家里然后失败的

**Comment by kougou888** [comment]
同问题蹲一个解决方案

**Comment by ysfuns** [comment]
> 你们都是部署在海外服务器的吗，有没有部署在家里然后失败的

就是家里失败的,和我们本身的部署无关,是验证的服务器出错了.

**Comment by MonkeyDTH** [comment]
遇到同一个问题了，蹲一下

**Comment by 1219099256** [comment]
刚刚认证过了，你们快试下

**Comment by MananaFX** [comment]
通过用户验证后 如果无法认证站点，可以使用代理认证

**Comment by trim21** [comment]
跟代理关系不大，API时好时坏的。

**Comment by kretro** [comment]
现在API是否可以 ，我一直不能登录

**Comment by MananaFX** [comment]
> 跟代理关系不大，API时好时坏的。

确实，过了站点验证，辅种任务的认证又失败了。先手动了

**Comment by zhengwenxiao** [comment]
同样的问题

**Comment by ledccn** [comment]
当前bug已修复；
引发bug的原因：大家的token是通过阿里云服务器，向腾讯云爱语飞飞服务器，发送消息的；因疏忽，未设置IP白名单，导致被限流。
