### ISSUE TITLE
群晖Docker模式建立db文件夹未见有具体作用

### ISSUE THREAD

**Issue by yepcn** [ledccn/IYUUPlus#19]
https://www.iyuu.cn/archives/426/
群晖Docker安装步骤第4步，映射了对应的文件夹，但是通过这两天使用来看，该db文件夹中并未有任何文件，不是很清楚装载这个路径的意义是什么。
plus版与AutoReseed版不同，AutoReseed版能够找到辅种缓存和辅种错误的目录，plus版暂时没有找到
是因为plus版没有另外生成文件还是什么情况？只能在Web页面进行清除辅种缓存么？

**Comment by ledccn** [comment]
应该是你映射的文件夹，容器内目录填写错了。（区分大小写的）
