### ISSUE TITLE
byr和北洋园辅种失败

### ISSUE THREAD

**Issue by wy-luke** [ledccn/IYUUPlus#27]
![Snipaste_2021-09-14_17-09-50](https://user-images.githubusercontent.com/25719685/133229955-8a285c85-b6f0-4d8a-bac4-843553ec4fb6.png)

错误提示如图

2021-09-14 16:56:35 (67a06d7) 最新版本的IYYUPlus
其他站点辅种正常
好像是因为站点种子的链接出问题了，我复制byr下载种子的连接，然后用qb从连接添加种子，就解析失败。试了猫站的就正常

**Comment by ledccn** [comment]
这种原因很好理解，站点把种子删除了；IYUUPlus的服务器没有同步到。
你忽略这种错误即可。

**Comment by wy-luke** [comment]
了解了，又试了一下，确实是你说的情况。蟹蟹！

**Comment by ledccn** [comment]
提醒：你的北洋passkey已经泄露，建议重置。
以后发图，注意隐私信息打马赛克。

**Comment by wy-luke** [comment]
> 提醒：你的北洋passkey已经泄露，建议重置。
> 以后发图，注意隐私信息打马赛克。

ok，已重置，感谢提醒~~
