### ISSUE TITLE
无法访问接口

### ISSUE THREAD

**Issue by GLORYFeonix** [ledccn/IYUUPlus#29]
![image](https://user-images.githubusercontent.com/50977527/135223305-5bec60f9-d7d9-4739-8012-5ca9b42ad8b7.png)
按照提示操作后问题仍然不能解决，重新安装IYUUPlus后问题依旧

**Comment by wy-luke** [comment]
也遇到了

**Comment by GrayXu** [comment]
@GLORYFeonix 类似的问题，请问你是怎么解决的？谢谢

**Comment by GrayXu** [comment]
> @GLORYFeonix 类似的问题，请问你是怎么解决的？谢谢

这个问题我是出现在修改了桥接网卡后出现的，参考[#1](https://github.com/ledccn/IYUUPlus/issues/1)添加了`--net=host`后工作正常。
