### ISSUE TITLE
请问 docker 版本，辅种怎么 skip_checking，谢谢！

### ISSUE THREAD

**Issue by pengkaiwei** [ledccn/IYUUPlus#32]
请问 docker 版本，辅种怎么 skip_checking

qb 跳过效验，还是会快速效验，不会影响站点上传数据 ，但是 可以节省很多时间。
请问大佬 docker 版本的辅种怎么开启 skip_checking
谢谢大佬！

**Comment by ledccn** [comment]
辅种不支持跳校验。
