### ISSUE TITLE
转移任务微信通知小bug/建议

### ISSUE THREAD

**Issue by terrance-liang** [ledccn/IYUUPlus#33]
位置 /src/Reseed/MoveTorrent.php#L310
标题内容：IYUU自动辅种-统计报表
建议修改：IYUU任务转移-统计报表

另外此任务通知中未添加对 ”notify_on_change“ 的检测，导致转移任务成功数量为0时发送空通知，例如：

> IYUU自动辅种-统计报表
> 版本号：2.0.6
> 此消息将在3天后过期。

非PHP程序员，暂不敢直接提交PR，辛苦开发者（们 ）:-)

另建议：站点下拉列表支持搜索或自动首字母匹配

**Comment by ledccn** [comment]
已完成。
