### ISSUE TITLE
关于辅种成功和失败的微信推送问题

### ISSUE THREAD

**Issue by hecarli555** [ledccn/IYUUPlus#35]
现在辅种失败也会推送感觉好烦，能否将辅种成功和失败＞0的判断分开两个开关设置，我想只需要成功的时候才给我微信推送，感谢大佬

**Comment by hecarli555** [comment]
为什么大佬不来解答啊

**Comment by hxsf** [comment]
solved by #38 
更新完试试看好不好用，好用就close这个issue，有问题直接留言

**Comment by hecarli555** [comment]
咱们iyuuplus镜像2个月没更新了吧………？何来更新



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 呼啸随风 ***@***.***&gt;
发送时间: 2021年11月25日 14:58
收件人: ledccn/IYUUPlus ***@***.***&gt;
抄送: hecarli555 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ledccn/IYUUPlus] 关于辅种成功和失败的微信推送问题 (Issue #35)





 
solved by #38
 更新完试试看好不好用，好用就close这个issue，有问题直接留言
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hxsf** [comment]
@hecarli555 大卫的镜像里好像是带了定时自动更新的

**Comment by hecarli555** [comment]
> @hecarli555 大卫的镜像里好像是带了定时自动更新的

好的，刚刚看了下，功能已经能实现了，非常棒！谢谢大佬提醒
