### ISSUE TITLE
发现一个问题，从服务器拉取的种子一部分非https

### ISSUE THREAD

**Issue by SUNJX97** [ledccn/IYUUPlus#36]
发现一个问题，从服务器拉取的种子一部分非https（在开启ssl连接tracker时），猜测是当时爬取种子时未开启或还未支持ssl连接tracker，导致这批种子的tracker链接都不是https的。希望在站点设置可以预设该站点种子tracker为https，对非https的拉取的非https的种子批量修正tracker。

**Comment by ledccn** [comment]
IYUUPlus内站点设置--》编辑对应站点，然后 附加参数--》勾选https

**Comment by SUNJX97** [comment]
> IYUUPlus内站点设置--》编辑对应站点，然后 附加参数--》勾选https

有的站点设置没有https参数，可以把这个开放给所有站点吗😂
