### ISSUE TITLE
【feature】排除站点删除种子导致的失败

### ISSUE THREAD

**Issue by hxsf** [ledccn/IYUUPlus#39]
https://github.com/ledccn/IYUUPlus/blob/1a2166512127e1cb428ba194497c1cd100739e12/src/Reseed/AutoReseed.php#L748-L751
此处使用 http HEAD 方式检测url是否 404 是否可行？

**Comment by ledccn** [comment]
按道理是可行的；
其实客户端使用transmission下载服务器的时候，会把出错的种子上报给IYUU服务器，在服务器端验证更好一些。
