### ISSUE TITLE
RSS计划任务，下载的数据目录不对

### ISSUE THREAD

**Issue by mjyhj** [ledccn/IYUUPlus#42]
数据目录怎么设置都无效

设置如下：
1.RSS计划任务里，数据目录留空
2.过滤器数据目录：/download3/电视剧
3.目录设置
![1](https://user-images.githubusercontent.com/22577418/145065616-fecc651b-7a0f-4cd1-822e-582d55cf7ff4.png)
4.映射目录
![2](https://user-images.githubusercontent.com/22577418/145065837-0cdc9981-6759-4714-8f19-f35f89a08490.png)
5.最终RSS自动下载到
![3](https://user-images.githubusercontent.com/22577418/145066071-6ab4c8c1-c8c8-4135-b42f-dc27f202c693.png)

**Comment by ledccn** [comment]
你对装载路径的理解是错误的，建议了解docker的机制。
