### ISSUE TITLE
是否可以将获取hash的客户端和发送hash的客户端分开

### ISSUE THREAD

**Issue by ProteinPig** [ledccn/IYUUPlus#47]
非单纯刷数据，自用的情况下，手头的站点多起来之后，一个种子在下载客户端重复出现一大片。

所以就在想是否可以正常下载的种子在客户端1，而辅种的种子在客户端2？（docker多开实例实现）

看了下辅种是从哪个客户端获取hash就发送到哪个客户端;转移做种是全部转移，连正常下的那个也转走了。

现有的功能是否能实现呢，还是需要添加新功能。

**Comment by ledccn** [comment]
技术上没难度；但相对于用户配置起来，docker挂载路径、容器内路径、宿主机路径、数据目录等这些概念，理解起来太复杂。

**Comment by ProteinPig** [comment]
目前使用flexget的qB_mod实现了，也是一样的体验。这个我就先关了。
