### ISSUE TITLE
已有种子辅种，能否自动修改资源的文件夹名称

### ISSUE THREAD

**Issue by byangmath** [ledccn/IYUUPlus#54]
用qb下载。由于要适配影音管理软件，修改了资源的文件夹名称，这样辅种就失败了。不知辅种时能否也自动相应地修改文件夹名称？
转种也会有同样的问题，不知是否能够解决。谢谢！

**Comment by byangmath** [comment]
转种也会有同样的问题，不知是否能够解决。谢谢！

**Comment by hxsf** [comment]
目录结构也是定义在种子里的，改了你就不能辅种了。
建议使用
1. pt单独下载目录。
2. 单独影音目录
3. 使用硬链接把需要的文件连接到单独影音目录。
至于硬链接用法，很容易搜索到。

比如 mklink(win), ln(unix), hlink(第三方工具) 等

**Comment by byangmath** [comment]
> 

我看qb里面会有.fastresume文件，里面记录了修改文件名后的映射关系，tr里面也有。没法自动获取.fastresume
文件内容然后辅种转种的时候进行改写么？我不太懂这个麻不麻烦，要是太麻烦就忽略我吧

**Comment by byangmath** [comment]
> 目录结构也是定义在种子里的，改了你就不能辅种了。 建议使用
> 
> 1. pt单独下载目录。
> 2. 单独影音目录
> 3. 使用硬链接把需要的文件连接到单独影音目录。
>    至于硬链接用法，很容易搜索到。
> 
> 比如 mklink(win), ln(unix), hlink(第三方工具) 等

我看qb里面会有.fastresume文件，里面记录了修改文件名后的映射关系，tr里面也有。没法自动获取.fastresume
文件内容然后辅种转种的时候进行改写么？我不太懂这个麻不麻烦，要是太麻烦就忽略我吧

**Comment by hxsf** [comment]
不了解是否可以做到。
但即使可以，程序怎么知道原路径是什么。而且程序不一定能读取到fastresume文件。
所以建议使用硬链接工具，或者单独拷贝一份。

**Comment by byangmath** [comment]
> 不了解是否可以做到。 但即使可以，程序怎么知道原路径是什么。而且程序不一定能读取到fastresume文件。 所以建议使用硬链接工具，或者单独拷贝一份。
好的，谢谢

**Comment by ledccn** [comment]
暂无计划
