### ISSUE TITLE
无法访问https://api.iyuu.cn接口，请检查本地网络；或重新创建容器，网络模式改为HOST模式

### ISSUE THREAD

**Issue by xjj2018** [ledccn/IYUUPlus#59]
平时用的好好的，突然出现这个“无法访问[https://api.iyuu.cn接口，请检查本地网络；或重新创建容器，网络模式改为HOST模式”

目前，重新安装了也不行。

这个怎么办？
![image](https://user-images.githubusercontent.com/42084482/159509556-35f64e78-31b5-4970-b54e-a2c6034bf0b4.png)

**Comment by gkgx163** [comment]
我也是这样，莫名其妙的哇

**Comment by xxy007zj** [comment]
防火墙开下端口试试

**Comment by HydraHuYu** [comment]
一样的问题 求解答
