### ISSUE TITLE
定时任务的任务/脚本内容，如果php的路径中包含空格，会导致任务运行失败

### ISSUE THREAD

**Issue by KeepNaivety3** [ledccn/IYUUPlus#61]
![image](https://jp.keepnaive233.network/Resources/temp15.png)
定时任务的任务/脚本内容，如果php的路径中包含空格，会导致任务运行失败
example:
php的环境变量在 `C:\Program Files\php\`  下，运行定时脚本会自己打开 `C:\Program` 文件夹，然后就没有动静了...

**Comment by xxy007zj** [comment]
win版教程不是写了吗“根目录”

**Comment by KeepNaivety3** [comment]
> win版教程不是写了吗“根目录”

教程写的是：
> 源码下载之后，解压到任意盘符的根目录下，双击`windows_install.cmd`即可。
但是出现问题是php的路径问题，环境变量中php的路径带空格导致的任务失败

**Comment by handsomexdd1024** [comment]
我是整了个C:\Runtimes文件夹，把gcc jdk php全放里面（
楼主可以参考一下

**Comment by ledccn** [comment]
建议路径不要包含空格。
