### ISSUE TITLE
自动辅种TR的文件夹名称错误

### ISSUE THREAD

**Issue by RenYueHD** [ledccn/IYUUPlus#67]
如题,假设A站源种的文件夹名称为   A1
IYUU自动辅种到B站,其种子文件夹名称为 A2
此时IYUU并不会将文件夹名称改为 A1,导致种子重新下载

希望能根据当前TR做种文件夹来重命名新种的文件夹

**Comment by ledccn** [comment]
辅种之后只会校验，不会重新下载；

**Comment by ledccn** [comment]
辅种的种子，只会校验；校验完成度100%的可以点开始，即可做种；不是100%的 直接移除即可，别点开始（开始的意思 就是开始下载）
