### ISSUE TITLE
QB转TR正常,TR转QB,目录错误

### ISSUE THREAD

**Issue by eschcn** [ledccn/IYUUPlus#70]
之前一直是用QB转TR，也都正常，但最近感觉还是QB管理起来更方便一些，又因为之前把QB的种子删了一部分，所以想用IYUU把种子从TR转回QB。
TR转QB看日志也是正常的
![IYUU)](https://i.ibb.co/DgwFgCw/QQ-20220607214531.png)

但是在QB客户端里看目录设置成默认目录downloads了。

![IYUU)](https://i.ibb.co/7Xkx4r9/QQ-20220607215024.png)

请问如何解决

**Comment by ledccn** [comment]
文档有说明：https://www.iyuu.cn/archives/451/
https://www.iyuu.cn/archives/465/

**Comment by bianyukun1213** [comment]
#113
