### ISSUE TITLE
辅种的种子添加至另外的下载器

### ISSUE THREAD

**Issue by sjtuross** [ledccn/IYUUPlus#74]
比如QB1是主下载器，辅种计划任务找到的辅种的种子添加至QB2下载器，这个能实现吗？

如果分成2个任务（辅种以及转移），貌似转移任务无法过滤出辅种任务添加的种子

**Comment by ledccn** [comment]
目前暂未实现。

**Comment by smallst** [comment]
所以目前辅种只能对当前下载器内的种子辅种是吗。 两个以上下载器只能先互相转种使两边同时做种后才能正常辅种全部种子？
