### ISSUE TITLE
qb转种tr，中途提示种子不存在

### ISSUE THREAD

**Issue by thsrite** [ledccn/IYUUPlus#76]
qb：4.4.3.1
tr：1.6.1
iyuu：2.0.7

名字：致命弯道系列.Wrong.Turn.1-6.2009-2014.BluRay.1080p.x265.10bit.MNHD-FRDS
********RPC添加下载任务成功 [success] (id=143)
转换前：/downloads/series
转换后：/downloads/series
存在种子：/qb/4ad28c737d25c4895af882841efcf60b18f9c530.torrent
种子已推送给下载器，正在转移做种...
名字：Bleach
********RPC添加下载任务成功 [success] (id=144)
转换前：/downloads/series
转换后：/downloads/series
存在种子：/qb/416a5859a976a16cedd6c2d7fe4707f3b3e0f2d6.torrent
种子已推送给下载器，正在转移做种...
名字：神印王座.Throne.of.Seal.2022.S01.2160p.WEB-DL.H265.AAC-LeagueWEB
********RPC添加下载任务成功 [success] (id=145)
转换前：/downloads/series
转换后：/downloads/series
存在种子：/qb/6971eae539bdd96af1b0d2f46b0618bcd969cee4.torrent
种子已推送给下载器，正在转移做种...
名字：诛仙.Jade.Dynasty.2022.S01.2160p.WEB-DL.H265.AAC-LeagueWEB
********RPC添加下载任务成功 [success] (id=146)
转换前：/downloads/movies
转换后：/downloads/movies
IYUU自动转移做种客户端--使用教程
https://www.iyuu.cn/archives/451/
https://www.iyuu.cn/archives/465/
clients_pid48_62c64424c3ab3 的种子文件/qb/c1ec7d62f8aaee1ef569c6f0545023b4009ac3bd.torrent不存在，无法完成转移！

**Comment by ArcherCX** [comment]
碰到相同问题， 用qbittorrent web api拉了种子列表比对了下，转种的时候出问题的种子infohash_v2和v1不为空，iyuu取了v2的值的一段（字符串长度等同于v1），但qb保存种子的时候用的是v1，导致两者没匹配上，直接中断了整个转种。

看docker和github的动态，估计等不到作者修了，附下简单操作定位问题流程：

1. curl（linux/windows powershell应该都默认就有）构造qb拉取种子列表的请求
`curl --cookie 'SUID=xxxx' http://qb_ip:qb_port/api/v2/torrents/info > torrents_info.txt`
cookie只要SUID就行，如果不验证登录应该不要也行，端口后接的api路径只在qb版本>=v4.1时有效，低版本api自行查看qb github的wiki
2. 直接搜报错种子的hash，查看该种子name，到qb里去搜下然后自己手动转种或删除啥的，最后再跑一遍转种任务应该就好了
