### ISSUE TITLE
辅种时出现类型错误，请大佬看下 Argument 3 passed to IYUU\Reseed\AutoReseed::requestApi() must be of the type int, string given, called in /IYUU/src/Reseed/AutoReseed.php on line 423 and defined in /IYUU/src/Reseed/AutoReseed.php:480

### ISSUE THREAD

**Issue by Dapong** [ledccn/IYUUPlus#82]
----------------------------------------memory_get_usage:65114112
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to IYUU\Reseed\AutoReseed::requestApi() must be of the type int, string given, called in /IYUU/src/Reseed/AutoReseed.php on line 423 and defined in /IYUU/src/Reseed/AutoReseed.php:480
Stack trace:
#0 /IYUU/src/Reseed/AutoReseed.php(423): IYUU\Reseed\AutoReseed::requestApi()
#1 /IYUU/src/Reseed/AutoReseed.php(374): IYUU\Reseed\AutoReseed::reseed()
#2 /IYUU/bin/iyuu.php(12): IYUU\Reseed\AutoReseed::call()
#3 {main}
  thrown in /IYUU/src/Reseed/AutoReseed.php on line 480
Fatal error: Uncaught TypeError: Argument 3 passed to IYUU\Reseed\AutoReseed::requestApi() must be of the type int, string given, called in /IYUU/src/Reseed/AutoReseed.php on line 423 and defined in /IYUU/src/Reseed/AutoReseed.php:480
Stack trace:
#0 /IYUU/src/Reseed/AutoReseed.php(423): IYUU\Reseed\AutoReseed::requestApi()
#1 /IYUU/src/Reseed/AutoReseed.php(374): IYUU\Reseed\AutoReseed::reseed()
#2 /IYUU/bin/iyuu.php(12): IYUU\Reseed\AutoReseed::call()
#3 {main}
  thrown in /IYUU/src/Reseed/AutoReseed.php on line 480
![image](https://user-images.githubusercontent.com/16550877/193705259-5544eaea-8ba2-4416-a4c0-fa7e2246d12f.png)

**Comment by fanhengyuan** [comment]
同样报错

**Comment by shanyan-wcx** [comment]
+1

**Comment by QingLiang2021** [comment]
+1

**Comment by fanhengyuan** [comment]
最近才开始使用，感谢大佬写出这么好的项目。
刚拉下代码初步看了下这个报错是 `/src/Reseed/AutoReseed.php` 文件中 `clientKey` 强类型问题
我打印我的 `clientKey` 是一个 字符串类型 `string`

**Comment by baiduren** [comment]
恢复 /src/Reseed/AutoReseed.php，好了

**Comment by nikolastang** [comment]
> 恢复 /src/Reseed/AutoReseed.php，好了

怎么恢复

**Comment by fanhengyuan** [comment]
@ledccn  `/src/Reseed/AutoReseed.php` 767行 k类型
