### ISSUE TITLE
辅种转种都出现问题了

### ISSUE THREAD

**Issue by Tracy1984** [ledccn/IYUUPlus#83]
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to IYUU\Reseed\AutoReseed::requestApi() must be of the type int, string given, called in /IYUU/src/Reseed/AutoReseed.php on line 426 and defined in /IYUU/src/Reseed/AutoReseed.php:480
Stack trace:
#0 /IYUU/src/Reseed/AutoReseed.php(426): IYUU\Reseed\AutoReseed::requestApi()
#1 /IYUU/src/Reseed/AutoReseed.php(374): IYUU\Reseed\AutoReseed::reseed()
#2 /IYUU/bin/iyuu.php(12): IYUU\Reseed\AutoReseed::call()
#3 {main}
  thrown in /IYUU/src/Reseed/AutoReseed.php on line 480
Fatal error: Uncaught TypeError: Argument 3 passed to IYUU\Reseed\AutoReseed::requestApi() must be of the type int, string given, called in /IYUU/src/Reseed/AutoReseed.php on line 426 and defined in /IYUU/src/Reseed/AutoReseed.php:480
Stack trace:
#0 /IYUU/src/Reseed/AutoReseed.php(426): IYUU\Reseed\AutoReseed::requestApi()
#1 /IYUU/src/Reseed/AutoReseed.php(374): IYUU\Reseed\AutoReseed::reseed()
#2 /IYUU/bin/iyuu.php(12): IYUU\Reseed\AutoReseed::call()
#3 {main}
  thrown in /IYUU/src/Reseed/AutoReseed.php on line 480

**Comment by sylee9695** [comment]
转种辅种都报错不能用

**Comment by ledccn** [comment]
函数参数我改为了强类型引起的bug；目前已修复。
