### ISSUE TITLE
docker镜像都是一年前的，不更新了吗

### ISSUE THREAD

**Issue by sylee9695** [ledccn/IYUUPlus#84]

**Comment by fanhengyuan** [comment]
docker 镜像中拉取的都是最新代码

**Comment by sylee9695** [comment]
> docker 镜像中拉取的都是最新代码
最新镜像，去年的
root@ubuntu:~# dc inspect iyuucn/iyuuplus
[
    {
        "Id": "sha256:6e59662bbf011e003d448dbf5ab73615a159e2a9033325c3b2f42e95346b7c7f",
        "RepoTags": [
            "iyuucn/iyuuplus:latest"
        ],
        "RepoDigests": [
            "iyuucn/iyuuplus@sha256:30e5fd50b5b7fbe8ff372cd9f6309c409683a469aee300413157c940c7b9f45b"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-09-15T05:56:53.278621823Z",

**Comment by ledccn** [comment]
镜像本身只是php的基础运行环境；镜像中会自动拉取最新代码；
