### ISSUE TITLE
qBittorrent v4.4.5 辅种失败

### ISSUE THREAD

**Issue by ceozero** [ledccn/IYUUPlus#86]
iyuu下载器设置中并没有设置到目录。
在4.3.9下辅种都正常。升级到4.4.5后无法识别到iyuu推送过来的目录了。

<img width="389" alt="截屏2022-10-08 00 43 25" src="https://user-images.githubusercontent.com/22513657/194605260-500daa0f-f10e-487b-a9b2-91f2d655bd86.png">
<img width="254" alt="截屏2022-10-08 00 44 04" src="https://user-images.githubusercontent.com/22513657/194605271-a54a634b-64f6-43b7-9341-a86e24685a01.png">

之前升级过一次后出现了转种无法推送tracker的问题，又降级使用。
看到这个问题解决以后才升级的。
https://github.com/ledccn/IYUUPlus/issues/49

**Comment by ledccn** [comment]
没用高版本测试过，我测试一下。

**Comment by ceozero** [comment]
应该是手贱改了自动管理种子了。
